---
- name: Install python module
  apt: name=python-mysqldb state=present

- name: setup mysql root user
  mysql_user:
    name: "{{ vault_mysql_username }}"
    password: "{{ vault_mysql_password }}"
    check_implicit_admin: true

- name: Modify mysql config file
  blockinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    marker: "#{mark} ANSIBLE MANAGED BLOCK"
    insertafter: "[mysqld]"
    block: |
      server_id       = 102
      log_bin         = mysql-bin
      log_slave_updates = 1
      relay_log       = mysql-relay-bin
      read_only       = 1

- name: Restart mysql service
  service: name=mysql state=restarted

- name: Stop slave if running
  command: /usr/bin/mysql -uroot -e "STOP SLAVE;"

- name: Setup replication
  command: /usr/bin/mysql -uroot -e "CHANGE MASTER TO master_host='10.10.10.51', master_user='{{ vault_mysql_replication_username }}', master_password='{{ vault_mysql_replication_password }}', master_ssl=1"

- name: Reset and start slave
  command: /usr/bin/mysql -uroot -e "RESET SLAVE; START SLAVE;"

